// Autogenerated from Pigeon (v3.2.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "SystemBootTime.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}



@interface SystemBootTimeCodecReader : FlutterStandardReader
@end
@implementation SystemBootTimeCodecReader
@end

@interface SystemBootTimeCodecWriter : FlutterStandardWriter
@end
@implementation SystemBootTimeCodecWriter
@end

@interface SystemBootTimeCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation SystemBootTimeCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[SystemBootTimeCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[SystemBootTimeCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *SystemBootTimeGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    SystemBootTimeCodecReaderWriter *readerWriter = [[SystemBootTimeCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void SystemBootTimeSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SystemBootTime> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.SystemBootTime.second"
        binaryMessenger:binaryMessenger
        codec:SystemBootTimeGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(secondWithError:)], @"SystemBootTime api (%@) doesn't respond to @selector(secondWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api secondWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
