// Autogenerated from Pigeon (v3.2.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by SystemBootTime.
NSObject<FlutterMessageCodec> *SystemBootTimeGetCodec(void);

@protocol SystemBootTime
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)secondWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SystemBootTimeSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<SystemBootTime> *_Nullable api);

NS_ASSUME_NONNULL_END
